### ISSUE TITLE
Handle multiple ponctuation

### ISSUE THREAD

**Issue by FabienGiely** [societe-generale/core-nlg#50]
For now only multiple dots are handled (".  ." --> ".")
It should also handle other ponctuation mark (", ," --> ",")

**Comment by rickdana** [comment]
Is this issue liked to the PR handle dots separated by tags #53 ? @FabienGiely ??

**Comment by FabienGiely** [comment]
PR #53 was about handling dots when they are separated by tags
In the comment i wrote :
".  < tag>." --> ". < tag>"

". ... < tag>." --> "... < tag>"

tags disappeared in the comment.

While this issue is about handling other ponctuations marks. 

It will be fixed by #54
